# Generated by Django 3.0.5 on 2020-04-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('commands', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='PlayBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hosts', models.CharField(max_length=100)),
                ('become', models.CharField(max_length=100)),
                ('become_method', models.CharField(max_length=100)),
                ('gather_facts', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Automation.Actions')),
            ],
        ),
    ]
