# Generated by Django 3.0.5 on 2020-05-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0003_c_hostname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='c_hostname',
        ),
    ]
