# Generated by Django 3.0.5 on 2020-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automation', '0004_delete_c_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hosts', models.CharField(max_length=255)),
            ],
        ),
    ]
